-- Initial schema migration for D1

-- Drop tables if they exist
DROP TABLE IF EXISTS TrendPoint;
DROP TABLE IF EXISTS Score;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Employee;

-- Create tables
CREATE TABLE Employee (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  wrongNumbers INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE User (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  hashedPassword TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('ADMIN', 'MANAGER', 'EMPLOYEE')) DEFAULT 'EMPLOYEE',
  employeeId INTEGER UNIQUE,
  createdAt TEXT NOT NULL DEFAULT (DATETIME('now')),
  updatedAt TEXT NOT NULL DEFAULT (DATETIME('now')),
  FOREIGN KEY (employeeId) REFERENCES Employee(id) ON DELETE CASCADE
);

CREATE TABLE Score (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  employeeId INTEGER NOT NULL UNIQUE,
  day INTEGER NOT NULL DEFAULT 75,
  week INTEGER NOT NULL DEFAULT 75,
  month INTEGER NOT NULL DEFAULT 75,
  updatedAt TEXT NOT NULL DEFAULT (DATETIME('now')),
  FOREIGN KEY (employeeId) REFERENCES Employee(id) ON DELETE CASCADE
);

CREATE TABLE TrendPoint (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  employeeId INTEGER NOT NULL,
  timestamp TEXT NOT NULL DEFAULT (DATETIME('now')),
  score INTEGER NOT NULL,
  FOREIGN KEY (employeeId) REFERENCES Employee(id) ON DELETE CASCADE
);

-- Triggers to update the updatedAt field
CREATE TRIGGER IF NOT EXISTS update_user_timestamp
AFTER UPDATE ON User
BEGIN
  UPDATE User SET updatedAt = DATETIME('now') WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS update_score_timestamp
AFTER UPDATE ON Score
BEGIN
  UPDATE Score SET updatedAt = DATETIME('now') WHERE id = NEW.id;
END; 