name = "react-tv-dashboard"
main = "src/worker.ts"
compatibility_date = "2023-09-22"

[build]
command = "bun run build"
watch_dir = "src"

[[d1_databases]]
binding = "DB"
database_name = "react_tv_dashboard"
database_id = "2c91e1ea85124136a1a690984a5e0eea"
migrations_dir = "d1/migrations"
migrations_table = "d1_migrations"

[[kv_namespaces]]
binding = "SESSION_STORE"
id = "2c91e1ea85124136a1a690984a5e0eea" # Replace with actual KV ID after creation

[site]
bucket = "./build/client"

[dev]
port = 8788
local_protocol = "http" 